language: python
sudo: false

python:
  - 2.7

install:
    - pip install https://github.com/cloudify-cosmo/cloudify-rest-client/archive/3.2m4.zip
    - pip install https://github.com/cloudify-cosmo/cloudify-dsl-parser/archive/3.2m4.zip
    - pip install https://github.com/cloudify-cosmo/cloudify-plugins-common/archive/3.2m4.zip
    - pip install https://github.com/cloudify-cosmo/cloudify-script-plugin/archive/1.2m4.zip
    - pip install https://github.com/cloudify-cosmo/cloudify-cli/archive/3.2m4.zip

env:
    - >
        OP=
        "
        cfy init;
        cfy blueprints validate -p cloudstack/cloudstack.yaml;
        "
    - OP="flake8 ."
    - >
        OP=
        "
        nose cloudstack/;
        nose openstack/;
        nose openstack-docker/;
        nose openstack-nova-net/;
        nose softlayer/;
        "

script:
#    - cfy init
#    - cfy blueprints validate -p cloudstack/cloudstack.yaml
#    - cfy blueprints validate -p openstack/openstack.yaml
#    - cfy blueprints validate -p openstack-docker/openstack-docker.yaml
#    - cfy blueprints validate -p openstack-nova-net/openstack.yaml
#    - cfy blueprints validate -p simple/simple.yaml
#    - cfy blueprints validate -p simple/simple-docker.yaml
#    - cfy blueprints validate -p softlayer/softlayer.yaml
#    - flake8 .
    - $(echo ${OP})
