language: python
sudo: false

python:
  - 2.7

install:
    - pip install https://github.com/cloudify-cosmo/cloudify-rest-client/archive/3.2m4.zip
    - pip install https://github.com/cloudify-cosmo/cloudify-dsl-parser/archive/3.2m4.zip
    - pip install https://github.com/cloudify-cosmo/cloudify-plugins-common/archive/3.2m4.zip
    - pip install https://github.com/cloudify-cosmo/cloudify-script-plugin/archive/1.2m4.zip
    - pip install https://github.com/cloudify-cosmo/cloudify-cli/archive/3.2m4.zip
    - pip install nose
    - pip install mock
    - pip install flake8

env:
    - OP="validate-blueprints"
    - OP="flake8"
    - OP="unit-tests"

script:
    - |
        set -e
        if [ "${OP}" == "validate-blueprints" ]; then
          cfy init
          cfy blueprints validate -p cloudstack/cloudstack.yaml
          cfy blueprints validate -p openstack/openstack.yaml
          cfy blueprints validate -p openstack-docker/openstack-docker.yaml
          cfy blueprints validate -p openstack-nova-net/openstack.yaml
          cfy blueprints validate -p simple/simple.yaml
          cfy blueprints validate -p simple/simple-docker.yaml
          cfy blueprints validate -p softlayer/softlayer.yaml
        elif [ "${OP}" == "flake8" ]; then
          flake8 .
        elif [ "${OP}" == "unit-tests" ]; then
          nosetests cloudstack/
          nosetests openstack/
          nosetests openstack-docker/
          nosetests openstack-nova-net/
          nosetests softlayer/
        else
          exit 1
        fi;

#notifications:
#    flowdock: 1f4ec6febcf1ac9b35ae6c1f0049471f
